---
- name: Update GRUB
  command: update-grub
  listen: update-grub
  failed_when: ('error' in grub_register_update.stderr)
  register: grub_register_update


- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
  listen: persist-iptables
