---
- hosts: drb
  
  vars_files:
    - vars.yml

  handlers:
    - name: Update GRUB
      command: update-grub
      listen: update-grub
      failed_when: ('error' in grub_register_update.stderr)
      register: grub_register_update


    - name: Save iptables rules
      shell: iptables-save > /etc/iptables/rules.v4
      listen: persist-iptables

  roles:
    - digital-rebar

  pre_tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - unzip
        - libcap2-bin
        - iptables-persistent

    - name: Create /usr/share/dr-provision
      file:
        path: /usr/share/dr-provision
        state: directory

    
    - name: Enable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        sysctl_set: yes


    - name: Set IP Masquerade
      iptables:
        table: nat
        chain: POSTROUTING
        out_interface: enp0s3
        jump: MASQUERADE
      notify: persist-iptables


    - name: Allow internal traffic to the outside
      iptables:
        chain: FORWARD
        in_interface: enp0s8
        out_interface: enp0s3
        jump: ACCEPT
      notify: persist-iptables


    - name: Allow related traffic from the outside back in
      iptables:
        chain: FORWARD
        in_interface: enp0s3
        out_interface: enp0s8
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT
      notify: persist-iptables


    # - name: Set GRUB kernel boot params
    #   lineinfile:
    #     path: /etc/default/grub
    #     regexp: '^GRUB_CMDLINE_LINUX='
    #     line: 'GRUB_CMDLINE_LINUX="debian-installer=en_US.UTF-8 net.ifnames=0 biosdevname=0"'
    #   notify: update-grub

  post_tasks:
    - name: Set capabilities on dr-provision binary
      capabilities:
        path: "{{ digital_rebar_binary }}"
        capability: cap_net_bind_service,cap_net_raw+ep
        state: present
      notify: restart dr-provision
